public enum State: String {
    case acre                   = "AC"
    case alagoas                = "AL"
    case amapá                  = "AP"
    case amazonas               = "AM"
    case bahia                  = "BA"
    case ceará                  = "CE"
    case distritoFederal        = "DF"
    case espíritoSanto          = "ES"
    case goiás                  = "GO"
    case maranhão               = "MA"
    case matoGrosso             = "MT"
    case matoGrossoDoSul        = "MS"
    case minasGerais            = "MG"
    case pará                   = "PA"
    case paraíba                = "PB"
    case paraná                 = "PR"
    case pernambuco             = "PE"
    case piauí                  = "PI"
    case rioDeJaneiro           = "RJ"
    case rioGrandeDoNorte       = "RN"
    case rioGrandeDoSul         = "RS"
    case rondônia               = "RO"
    case roraima                = "RR"
    case santaCatarina          = "SC"
    case sãoPaulo               = "SP"
    case sergipe                = "SE"
    case tocantins              = "TO"

    var name: String {
        switch self {
        case .acre:              return "Acre"
        case .alagoas:           return "Alagoas"
        case .amapá:             return "Amapá"
        case .amazonas:          return "Amazonas"
        case .bahia:             return "Bahia"
        case .ceará:             return "Ceará"
        case .distritoFederal:   return "Distrito Federal"
        case .espíritoSanto:     return "Espírito Santo"
        case .goiás:             return "Goiás"
        case .maranhão:          return "Maranhão"
        case .matoGrosso:        return "Mato Grosso"
        case .matoGrossoDoSul:   return "Mato Grosso do Sul"
        case .minasGerais:       return "Minas Gerais"
        case .pará:              return "Pará"
        case .paraíba:           return "Paraíba"
        case .paraná:            return "Paraná"
        case .pernambuco:        return "Pernambuco"
        case .piauí:             return "Piauí"
        case .rioDeJaneiro:      return "Rio de Janeiro"
        case .rioGrandeDoNorte:  return "Rio Grande do Norte"
        case .rioGrandeDoSul:    return "Rio Grande do Sul"
        case .rondônia:          return "Rondônia"
        case .roraima:           return "Roraima"
        case .santaCatarina:     return "Santa Catarina"
        case .sãoPaulo:          return "São Paulo"
        case .sergipe:           return "Sergipe"
        case .tocantins:         return "Tocantins"
        }
    }
}
