public enum State: String {
    case Acre                   = "AC"
    case Alagoas                = "AL"
    case Amapá                  = "AP"
    case Amazonas               = "AM"
    case Bahia                  = "BA"
    case Ceará                  = "CE"
    case DistritoFederal        = "DF"
    case EspíritoSanto          = "ES"
    case Goiás                  = "GO"
    case Maranhão               = "MA"
    case MatoGrosso             = "MT"
    case MatoGrossoDoSul        = "MS"
    case MinasGerais            = "MG"
    case Pará                   = "PA"
    case Paraíba                = "PB"
    case Paraná                 = "PR"
    case Pernambuco             = "PE"
    case Piauí                  = "PI"
    case RioDeJaneiro           = "RJ"
    case RioGrandeDoNorte       = "RN"
    case RioGrandeDoSul         = "RS"
    case Rondônia               = "RO"
    case Roraima                = "RR"
    case SantaCatarina          = "SC"
    case SãoPaulo               = "SP"
    case Sergipe                = "SE"
    case Tocantins              = "TO"

    var name: String {
        switch self {
        case Acre:              return "Acre"
        case Alagoas:           return "Alagoas"
        case Amapá:             return "Amapá"
        case Amazonas:          return "Amazonas"
        case Bahia:             return "Bahia"
        case Ceará:             return "Ceará"
        case DistritoFederal:   return "Distrito Federal"
        case EspíritoSanto:     return "Espírito Santo"
        case Goiás:             return "Goiás"
        case Maranhão:          return "Maranhão"
        case MatoGrosso:        return "Mato Grosso"
        case MatoGrossoDoSul:   return "Mato Grosso do Sul"
        case MinasGerais:       return "Minas Gerais"
        case Pará:              return "Pará"
        case Paraíba:           return "Paraíba"
        case Paraná:            return "Paraná"
        case Pernambuco:        return "Pernambuco"
        case Piauí:             return "Piauí"
        case RioDeJaneiro:      return "Rio de Janeiro"
        case RioGrandeDoNorte:  return "Rio Grande do Norte"
        case RioGrandeDoSul:    return "Rio Grande do Sul"
        case Rondônia:          return "Rondônia"
        case Roraima:           return "Roraima"
        case SantaCatarina:     return "Santa Catarina"
        case SãoPaulo:          return "São Paulo"
        case Sergipe:           return "Sergipe"
        case Tocantins:         return "Tocantins"
        }
    }
}
